src/NAC_Service_Portal/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("", include("nac.urls")),
]

src/nac/urls.py
from django.urls import path
from .subviews.home import HomePageView

from .subviews.device_management import (
    DeviceListView,
    DeviceListCsvView,
    DeviceDetailView,
    DeviceUpdateView,
    DeviceDeleteView,
    DeviceCreateView,
)

from .subviews.autocomplete import (
    DNSDomainAutocomplete,
    DeviceRoleProdAutocomplete,
    AdministrationGroupAutocomplete,
)

from .subviews.account import (
    AccountSettings,
    change_password,
)

from .subviews.armis import ArmisView
from .subviews.file_import import FileImportView


urlpatterns = [
    path("", HomePageView.as_view(), name="home"),
    path("devices/", DeviceListView.as_view(), name="devices"),
    path("devices/export", DeviceListCsvView.as_view(), name="device_export_csv"),
    path("devices/<int:pk>/", DeviceDetailView.as_view(), name="device_detail"),
    path("devices/<int:pk>/edit/", DeviceUpdateView.as_view(), name="device_edit"),
    path("devices/<int:pk>/delete", DeviceDeleteView.as_view(), name="device_delete"),
    path("devices/new/", DeviceCreateView.as_view(), name="device_new"),
    path("armis/", ArmisView.as_view(), name="armis_import"),
    path("file_import/", FileImportView.as_view(), name="file_import"),
    path("dns_domain-autocomplete/", DNSDomainAutocomplete.as_view(), name="dns_domain-autocomplete"),
    path("DeviceRoleProd-autocomplete/", DeviceRoleProdAutocomplete.as_view(), name="DeviceRoleProd-autocomplete"),
    path("administration-group-autocomplete/", AdministrationGroupAutocomplete.as_view(), name="administration-group-autocomplete"),
    path("account-settings/", AccountSettings.as_view(), name="account-settings"),
    path("change_password/", change_password, name='change_password'),
]

src/nac/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.urls import reverse
from simple_history.models import HistoricalRecords


class DeviceRoleProd(models.Model):
    name = models.TextField()

    def __str__(self):
        return self.name[:50]


class DNSDomain(models.Model):
    name = models.TextField()

    def __str__(self):
        return self.name[:50]


class AdministrationGroup(models.Model):
    name = models.TextField()
    DeviceRoleProd = models.ManyToManyField(DeviceRoleProd)

    def __str__(self):
        return self.name[:50]


class CustomUser(AbstractUser):
    administration_group = models.ManyToManyField(AdministrationGroup)

    def __str__(self):
        return self.username


class Device(models.Model):
    asset_id = models.CharField(null=True, blank=True, max_length=150, verbose_name="Asset ID")
    administration_group = models.ForeignKey(AdministrationGroup, on_delete=models.SET_NULL, null=True, verbose_name="Administration Group")
    appl_NAC_DeviceRoleProd = models.ForeignKey(
        DeviceRoleProd, on_delete=models.SET_NULL, null=True, verbose_name="Device role productive")
    synchronized = models.BooleanField(null=True, default=False)

    dns_domain = models.ForeignKey(DNSDomain, on_delete=models.SET_NULL, null=True, verbose_name="DNS domain")
    vlan = models.CharField(null=True, blank=True, max_length=100, verbose_name="VLAN")
    source = models.CharField(null=True, blank=True, max_length=100, verbose_name="Data origin")
    modified_by = models.ForeignKey(CustomUser, on_delete=models.SET_NULL, null=True, blank=True)
    last_modified = models.TextField(null=True, blank=True, editable=False, verbose_name="Time of last modification")
    creationDate = models.TextField(null=True, blank=True, editable=False, verbose_name="Time of creation")

    additional_info = models.TextField(null=True, blank=True, verbose_name="Additional information")
    appl_NAC_Hostname = models.CharField(null=True, max_length=63, verbose_name="Hostname")
    appl_NAC_Active = models.BooleanField(null=True, default=True, verbose_name="Active (access allowed)")
    appl_NAC_ForceDot1X = models.BooleanField(null=True, default=True, verbose_name="Force 802.1X")
    appl_NAC_Install = models.BooleanField(null=True, verbose_name="Installation")
    allowLdapSync = models.BooleanField(null=True, default=False, verbose_name="Sync with LDAP allowed")
    appl_NAC_AllowAccessCAB = models.BooleanField(null=True, default=True, verbose_name="Wired access allowed")
    appl_NAC_AllowAccessAIR = models.BooleanField(null=True, verbose_name="Wireless access allowed")
    appl_NAC_AllowAccessVPN = models.BooleanField(null=True, verbose_name="VPN access allowed")
    appl_NAC_AllowAccessCEL = models.BooleanField(null=True, verbose_name="Cellular access allowed")
    appl_NAC_macAddressCAB = models.TextField(null=True,
                                              blank=True, unique=True, verbose_name="Wired MAC address")
    appl_NAC_macAddressAIR = models.CharField(null=True, max_length=100,
                                              blank=True, unique=True, verbose_name="Wireless MAC address")
    appl_NAC_Certificate = models.TextField(null=True, blank=True, verbose_name="Certificate")
    deleted = models.BooleanField(null=True, default=False, verbose_name="Deleted")
    history = HistoricalRecords()

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=[
                'appl_NAC_Hostname',
                'dns_domain'
            ], name='unique_fqdn')
        ]

    @property
    def appl_NAC_FQDN(self):
        return f'{self.appl_NAC_Hostname}.{self.dns_domain}'

    def save(self, *args, **kwargs):
        if not self.asset_id:
            self.asset_id = f"FQDN_{self.appl_NAC_FQDN}"
        super().save(*args, **kwargs)

    def __str__(self):
        return self.appl_NAC_Hostname[:100]

    def get_absolute_url(self):
        return reverse("device_detail", kwargs={"pk": self.pk})

    def format_mac(self, mac):
        mac = mac.upper()
        return ":".join(mac[i:i+2] for i in range(0, 12, 2))

    def get_appl_NAC_macAddressAIR(self):
        if not self.appl_NAC_macAddressAIR:
            return None
        return [self.format_mac(mac) for mac in
                self.appl_NAC_macAddressAIR.split(",")]

    def get_appl_NAC_macAddressCAB(self):
        if not self.appl_NAC_macAddressCAB:
            return None
        return [self.format_mac(mac) for mac in
                self.appl_NAC_macAddressCAB.split(",")]

src/templates/account_settings.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    <h1>Account Settings</h1>
    <a class="btn btn-secondary btn-sm" style="color: white;" href="{% url 'change_password' %}">Change password</a>
</div>
{% endblock content %}

src/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		
		<title>{% block title %}NAC Self-Service-Portal{% endblock %}</title>

		<!-- Bootstrap CSS -->
		<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

		<link rel="stylesheet" href="{% static 'default.css' %}">

		<link rel="icon" href="{% static 'icons/favicon.svg' %}" sizes="any" type="image/svg+xml">
		
		<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

		<!-- JQuery -->
		<script src="https://code.jquery.com/jquery-3.7.1.js" integrity="sha256-eKhayi8LEQwp4NKxN+CfCh+3qOVUtJn3QNZ0TciWLP4=" crossorigin="anonymous"></script>
		
		{% block head %}{% endblock %}
	</head>

	<body>
		<nav class="navbar navbar-expand-lg bg-body-tertiary">
			<div class="container-fluid">
				<a class="navbar-brand" href="/">
					<svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" fill="currentColor" class="bi bi-ethernet" viewBox="0 0 16 16">
						<path d="M14 13.5v-7a.5.5 0 0 0-.5-.5H12V4.5a.5.5 0 0 0-.5-.5h-1v-.5A.5.5 0 0 0 10 3H6a.5.5 0 0 0-.5.5V4h-1a.5.5 0 0 0-.5.5V6H2.5a.5.5 0 0 0-.5.5v7a.5.5 0 0 0 .5.5h11a.5.5 0 0 0 .5-.5M3.75 11h.5a.25.25 0 0 1 .25.25v1.5a.25.25 0 0 1-.25.25h-.5a.25.25 0 0 1-.25-.25v-1.5a.25.25 0 0 1 .25-.25m2 0h.5a.25.25 0 0 1 .25.25v1.5a.25.25 0 0 1-.25.25h-.5a.25.25 0 0 1-.25-.25v-1.5a.25.25 0 0 1 .25-.25m1.75.25a.25.25 0 0 1 .25-.25h.5a.25.25 0 0 1 .25.25v1.5a.25.25 0 0 1-.25.25h-.5a.25.25 0 0 1-.25-.25zM9.75 11h.5a.25.25 0 0 1 .25.25v1.5a.25.25 0 0 1-.25.25h-.5a.25.25 0 0 1-.25-.25v-1.5a.25.25 0 0 1 .25-.25m1.75.25a.25.25 0 0 1 .25-.25h.5a.25.25 0 0 1 .25.25v1.5a.25.25 0 0 1-.25.25h-.5a.25.25 0 0 1-.25-.25z"/>
						<path d="M2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2zM1 2a1 1 0 0 1 1-1h12a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1z"/>
					</svg>
					NSSP
				</a>
				<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
					<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-justify" viewBox="0 0 16 16">
						<path fill-rule="evenodd" d="M2 12.5a.5.5 0 0 1 .5-.5h11a.5.5 0 0 1 0 1h-11a.5.5 0 0 1-.5-.5m0-3a.5.5 0 0 1 .5-.5h11a.5.5 0 0 1 0 1h-11a.5.5 0 0 1-.5-.5m0-3a.5.5 0 0 1 .5-.5h11a.5.5 0 0 1 0 1h-11a.5.5 0 0 1-.5-.5m0-3a.5.5 0 0 1 .5-.5h11a.5.5 0 0 1 0 1h-11a.5.5 0 0 1-.5-.5"/>
					</svg>
				</button>
				<div class="collapse navbar-collapse" id="navbarSupportedContent">
					<ul class="navbar-nav me-auto mb-2 mb-lg-0">
						{% block navbar %}{% endblock %}
						{% if user.is_authenticated %}
						<li class="nav-item">
							<a class="nav-link active" aria-current="page" href="{% url 'devices' %}">
								<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-card-list" viewBox="0 0 16 16">
									<path d="M14.5 3a.5.5 0 0 1 .5.5v9a.5.5 0 0 1-.5.5h-13a.5.5 0 0 1-.5-.5v-9a.5.5 0 0 1 .5-.5zm-13-1A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h13a1.5 1.5 0 0 0 1.5-1.5v-9A1.5 1.5 0 0 0 14.5 2z"/>
									<path d="M5 8a.5.5 0 0 1 .5-.5h7a.5.5 0 0 1 0 1h-7A.5.5 0 0 1 5 8m0-2.5a.5.5 0 0 1 .5-.5h7a.5.5 0 0 1 0 1h-7a.5.5 0 0 1-.5-.5m0 5a.5.5 0 0 1 .5-.5h7a.5.5 0 0 1 0 1h-7a.5.5 0 0 1-.5-.5m-1-5a.5.5 0 1 1-1 0 .5.5 0 0 1 1 0M4 8a.5.5 0 1 1-1 0 .5.5 0 0 1 1 0m0 2.5a.5.5 0 1 1-1 0 .5.5 0 0 1 1 0"/>
								</svg>
								Device List
							</a>
						</li>
						<li class="nav-item">
							<a class="nav-link active" aria-current="page" href="{% url 'device_new' %}">
								<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pc-display-horizontal" viewBox="0 0 16 16">
									<path d="M12.5 16a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7m.5-5v1h1a.5.5 0 0 1 0 1h-1v1a.5.5 0 0 1-1 0v-1h-1a.5.5 0 0 1 0-1h1v-1a.5.5 0 0 1 1 0"/>
									<path d="M13.5 3a.5.5 0 0 1 .5.5V11H2V3.5a.5.5 0 0 1 .5-.5zm-11-1A1.5 1.5 0 0 0 1 3.5V12h14V3.5A1.5 1.5 0 0 0 13.5 2zM0 12.5h16a1.5 1.5 0 0 1-1.5 1.5h-13A1.5 1.5 0 0 1 0 12.5"/>
								</svg>
								Add Device
							</a>
						</li>
						{% if armis_is_configured %}
						<li class="nav-item">
							<a class="nav-link active" aria-current="page" href="{% url 'armis_import' %}">
								<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-cloud-arrow-down" viewBox="0 0 16 16">
									<path fill-rule="evenodd" d="M7.646 10.854a.5.5 0 0 0 .708 0l2-2a.5.5 0 0 0-.708-.708L8.5 9.293V5.5a.5.5 0 0 0-1 0v3.793L6.354 8.146a.5.5 0 1 0-.708.708z"/>
									<path d="M4.406 3.342A5.53 5.53 0 0 1 8 2c2.69 0 4.923 2 5.166 4.579C14.758 6.804 16 8.137 16 9.773 16 11.569 14.502 13 12.687 13H3.781C1.708 13 0 11.366 0 9.318c0-1.763 1.266-3.223 2.942-3.593.143-.863.698-1.723 1.464-2.383m.653.757c-.757.653-1.153 1.44-1.153 2.056v.448l-.445.049C2.064 6.805 1 7.952 1 9.318 1 10.785 2.23 12 3.781 12h8.906C13.98 12 15 10.988 15 9.773c0-1.216-1.02-2.228-2.313-2.228h-.5v-.5C12.188 4.825 10.328 3 8 3a4.53 4.53 0 0 0-2.941 1.1z"/>
								</svg>
								Armis Import
							</a>
						</li>
						{% endif %}
						<li class="nav-item">
							<a class="nav-link active" aria-current="page" href="{% url 'file_import' %}">
								<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-file-earmark-arrow-down" viewBox="0 0 16 16">
									<path d="M8.5 6.5a.5.5 0 0 0-1 0v3.793L6.354 9.146a.5.5 0 1 0-.708.708l2 2a.5.5 0 0 0 .708 0l2-2a.5.5 0 0 0-.708-.708L8.5 10.293z"/>
									<path d="M14 14V4.5L9.5 0H4a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2M9.5 3A1.5 1.5 0 0 0 11 4.5h2V14a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h5.5z"/>
								</svg>
								File Import
							</a>
						</li>
							<a class="nav-link active" aria-current="page" href="{% url 'account-settings' %}">
								<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-gear" viewBox="0 0 16 16">
									<path d="M11 5a3 3 0 1 1-6 0 3 3 0 0 1 6 0M8 7a2 2 0 1 0 0-4 2 2 0 0 0 0 4m.256 7a4.5 4.5 0 0 1-.229-1.004H3c.001-.246.154-.986.832-1.664C4.484 10.68 5.711 10 8 10q.39 0 .74.025c.226-.341.496-.65.804-.918Q8.844 9.002 8 9c-5 0-6 3-6 4s1 1 1 1zm3.63-4.54c.18-.613 1.048-.613 1.229 0l.043.148a.64.64 0 0 0 .921.382l.136-.074c.561-.306 1.175.308.87.869l-.075.136a.64.64 0 0 0 .382.92l.149.045c.612.18.612 1.048 0 1.229l-.15.043a.64.64 0 0 0-.38.921l.074.136c.305.561-.309 1.175-.87.87l-.136-.075a.64.64 0 0 0-.92.382l-.045.149c-.18.612-1.048.612-1.229 0l-.043-.15a.64.64 0 0 0-.921-.38l-.136.074c-.561.305-1.175-.309-.87-.87l.075-.136a.64.64 0 0 0-.382-.92l-.148-.045c-.613-.18-.613-1.048 0-1.229l.148-.043a.64.64 0 0 0 .382-.921l-.074-.136c-.306-.561.308-1.175.869-.87l.136.075a.64.64 0 0 0 .92-.382zM14 12.5a1.5 1.5 0 1 0-3 0 1.5 1.5 0 0 0 3 0"/>
								</svg>
								Account Settings
							</a>
						</li>
						<li class="nav-item">
							<form method="post" action="{% url 'logout' %}" class="inline">
								{% csrf_token %}
								<button type="submit" class="link-button" style="margin-top: 6px;">
									<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-box-arrow-right" viewBox="0 0 16 16">
										<path fill-rule="evenodd" d="M10 12.5a.5.5 0 0 1-.5.5h-8a.5.5 0 0 1-.5-.5v-9a.5.5 0 0 1 .5-.5h8a.5.5 0 0 1 .5.5v2a.5.5 0 0 0 1 0v-2A1.5 1.5 0 0 0 9.5 2h-8A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h8a1.5 1.5 0 0 0 1.5-1.5v-2a.5.5 0 0 0-1 0z"/>
										<path fill-rule="evenodd" d="M15.854 8.354a.5.5 0 0 0 0-.708l-3-3a.5.5 0 0 0-.708.708L14.293 7.5H5.5a.5.5 0 0 0 0 1h8.793l-2.147 2.146a.5.5 0 0 0 .708.708z"/>
									</svg>
									Logout ({{ user.username }})
								</button>
							</form>
						</li>
						{% else %}
						<li class="nav-item">
							<a class="nav-link active" aria-current="page" href="{% url 'login' %}">
								<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-box-arrow-in-right" viewBox="0 0 16 16">
									<path fill-rule="evenodd" d="M6 3.5a.5.5 0 0 1 .5-.5h8a.5.5 0 0 1 .5.5v9a.5.5 0 0 1-.5.5h-8a.5.5 0 0 1-.5-.5v-2a.5.5 0 0 0-1 0v2A1.5 1.5 0 0 0 6.5 14h8a1.5 1.5 0 0 0 1.5-1.5v-9A1.5 1.5 0 0 0 14.5 2h-8A1.5 1.5 0 0 0 5 3.5v2a.5.5 0 0 0 1 0z"/>
									<path fill-rule="evenodd" d="M11.854 8.354a.5.5 0 0 0 0-.708l-3-3a.5.5 0 1 0-.708.708L10.293 7.5H1.5a.5.5 0 0 0 0 1h8.793l-2.147 2.146a.5.5 0 0 0 .708.708z"/>
								</svg>
								Login
							</a>
						</li>
					{% endif %}
					</ul>
				</div>
			</div>
		</nav>
	
	{% block content %}
	{% endblock %}

	{% block footer %}
	{% endblock footer %}

	</body>
</html>

src/templates/change_password.html
{% extends "base.html" %}
{% block content %}
  {% load static %}
  {% load crispy_forms_tags %}
      <div class="container">
        <form method="post">
        {% csrf_token %}
        {{ form | crispy }}
        <button type="submit" class="btn btn-secondary btn-sm">Save changes</button>
        </form>
      </div>
{% endblock content %}

src/templates/device_delete.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="container">
	<h1>Delete</h1>
	<form action="" method="post">{% csrf_token %}
	    <p>Are you sure you want to delete "{{ device.appl_NAC_FQDN }}"?</p>
	    <button type="submit" class="btn btn-primary btn-block">
			<svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
				<path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5m2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5m3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0z"/>
				<path d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4zM2.5 3h11V2h-11z"/>
			</svg>
			Confirm
		</button>
	</form>
</div>
{% endblock content %}

src/templates/device_edit.html
{% extends "base.html" %}

{% block content %}
{%load crispy_forms_tags %}

<div class="container">
    <h1>Reset device</h1>
    {% crispy device_history_form %}
    <br>
    <h1>Edit device</h1>
    {% include "device_form.html" %}
</div>
{% endblock content %}

src/templates/device_form.html
{% load static %}
{% load crispy_forms_tags %}

<form method="post">
    {% csrf_token %}
    <div class="form-check form-switch">
        {{ form.deleted }}
        {{ form.deleted.label_tag|cut:":" }}
    </div>
    {{ form.asset_id|as_crispy_field }}
    {{ form.administration_group|as_crispy_field }}
    <div class="row">
        <div class="col-md-6">
            {{ form.appl_NAC_Hostname|as_crispy_field }}
        </div>
        <div class="col-md-6">
            {{ form.dns_domain|as_crispy_field }}
        </div>
    </div>
    {{ form.appl_NAC_DeviceRoleProd|as_crispy_field }}
    {% if form.vlan.value %}
        {{ form.vlan|as_crispy_field }}
    {% endif %}

    <div class="row">
        <div class="column">
            {{ form.appl_NAC_Active | as_crispy_field }}
            <ul class="list-unstyled" style="padding-left: 2em">
                <li>{{ form.appl_NAC_AllowAccessVPN | as_crispy_field }}</li>
                <li>{{ form.appl_NAC_AllowAccessCEL | as_crispy_field }}</li>
                <li>{{ form.appl_NAC_AllowAccessCAB | as_crispy_field }}</li>
                <li><span class="monospace">{{ form.appl_NAC_macAddressCAB | as_crispy_field }}</span></li>
                <li>{{ form.appl_NAC_AllowAccessAIR | as_crispy_field }}</li>
                <li><span class="monospace">{{ form.appl_NAC_macAddressAIR | as_crispy_field }}</span></li>
            </ul>
        </div>
        <div class="column">
            {{ form.allowLdapSync | as_crispy_field }}
            {{ form.appl_NAC_ForceDot1X | as_crispy_field }}
            {{ form.appl_NAC_Install | as_crispy_field }}
        </div>
    </div>
    {{ form.additional_info | as_crispy_field }}
    {{ form.source | as_crispy_field }}
    <div class="mb-4">
        <button type="submit" class="btn btn-secondary btn-sm">Save</button>
        <a href="{% url 'devices' %}" class="btn btn-secondary btn-sm" style="color: white;">Cancel</a>
    </div>
</form>

<script type="text/javascript" src="{% static 'admin/js/vendor/jquery/jquery.js' %}"></script>
<script type="text/javascript">
    $(document).ready(function() {
    // Bind on continent field change
    $(':input[name$=administration_group]').on('change', function() {
        // Get the field prefix, ie. if this comes from a formset form
        var prefix = $(this).getFormPrefix();

        // Clear the autocomplete with the same prefix
        $(':input[name=' + prefix + 'appl_NAC_DeviceRoleProd]').val(null).trigger('change');
    });
});
</script>

<script>
    document.addEventListener("DOMContentLoaded", function() {
        const checkboxes = document.querySelectorAll('.checkbox');
        const activeCheckbox = document.querySelector('#id_appl_NAC_Active');
        const vpnCheckbox = document.querySelector('#id_appl_NAC_AllowAccessVPN');
        const celCheckbox = document.querySelector('#id_appl_NAC_AllowAccessCEL');
        const cabCheckbox = document.querySelector('#id_appl_NAC_AllowAccessCAB');
        const airCheckbox = document.querySelector('#id_appl_NAC_AllowAccessAIR');

        const accessCheckboxes = [vpnCheckbox, celCheckbox, cabCheckbox, airCheckbox];

        // grey out access checkboxes if "Active" flag is not set
        function updateActiveStatus() {
            for (let i=0; i<accessCheckboxes.length; i++) {
                if (activeCheckbox.checked) {
                    accessCheckboxes[i].classList.remove('greyed-out');
                } else {
                    accessCheckboxes[i].classList.add('greyed-out');
                }
            }
        }

        // Initial check when the page loads
        updateActiveStatus();

        // Add event listener to the active checkbox to trigger grey out on change
        activeCheckbox.addEventListener('change', updateActiveStatus);
    });
</script>

<style>
    .row {
        display: flex;
    }

    .column {
      flex: 50%;
    }

    .greyed-out {
      opacity: 0.5;
    }
</style>

{{ form.media }}

src/templates/device_new.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    <h1>New device</h1>
    {% include "device_form.html" %}
</div>
{% endblock content %}

src/templates/devices.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container">
	<h1>Filter</h1>
	<span class="icon-desc" desc="Reset filter"><a class="btn btn-secondary btn-sm" style="color: white;" href="{% url 'devices' %}">
		<img src="{% static 'icons/trash3.svg' %}" alt="Reset" height="16" width="16"/>
	</a></span>
	<form id="search_form" action="{% url 'devices' %}" method="get">
		<div class="row">
			{% for field in search_form %}
				<div class="col-auto">
					{{ field | as_crispy_field }}
				</div>
			{% endfor %}
		</div>

		<h1>Devices</h1>
		<div style="display: flex; justify-content: space-between;">
		<span class="icon-desc" desc="Refresh results"><button type="submit" class="btn btn-secondary btn-sm">
			<img src="{% static 'icons/arrow-clockwise.svg' %}" alt="Refresh" height="18" width="18"/>
		</button></span>
		<span>
			<button type="submit" class="btn btn-secondary btn-sm" formaction="{% url 'device_export_csv' %}?export=csv">Export as CSV</button>
		</span>
		</div>
	</form>
	<form method="post">
    	{% csrf_token %}
		<button type="submit" class="btn btn-secondary btn-sm">Resync</button>
	</form>
	<div id="results">
		{% include "devices_results.html" %}
	</div>
</div>

<script type="text/javascript" src="{% static 'device_filtering.js' %}"></script>

{% endblock content %}